[build]
  publish = "."

[[redirects]]
  from = "/api/groq"
  to = "/.netlify/functions/groq-proxy"
  status = 200

[[redirects]]
  from = "/api/ml"
  to = "/.netlify/functions/ml-proxy"
  status = 200

[[redirects]]
  from = "/api/tavily"
  to = "/.netlify/functions/tavily-proxy"
  status = 200

[[redirects]]
  from = "/api/ml-token"
  to = "/.netlify/functions/ml-token"
  status = 200

[[redirects]]
  from = "/api/ml-search"
  to = "/.netlify/functions/ml-search"
  status = 200
